// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var template;

  template = require('./template');

  module.exports = {
    html: "" + template.header + "\n  \n  <p>\n    Se ha creado esta nueva solicitude \"<%= title %>\" con codigo: <%= code %>.\n  </p>\n  <a class=\"ir\" href=\"<%= url %>\">Ir a la Solicitud</a>\n\n" + template.footer,
    text: "Se ha creado esta nueva solicitude \"<%= title %>\" con codigo: <%= code %>.\nlink: <%= url %>"
  };

}).call(this);
