// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var template;

  template = require('./template');

  module.exports = {
    html: "" + template.header + "\n\n  <p>\n    <%= to %> la solicitud \"<%= title %>\" con código de referencia <b><%= code %></b>, a actualizado su estado a <b><%= state.toLowerCase() %></b> para acceder a ella solo debes hacer click <a class=\"ir\" href=\"<%= url %>\">aquí</a>. \n  </p>\n\n" + template.footer,
    text: "<%= to %> la solicitud \"<%= title %>\" con código de referencia <b><%= code %></b>, a actualizado su estado a <b><%= state.toLowerCase() %></b>.\nlink: <%= url %>"
  };

}).call(this);
