// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var template;

  template = require('./template');

  module.exports = {
    html: template.header + "\n\n  <p>\n    La solicitud \"<%= title %>\", con código de referencia <b><%= code %></b>, ha sido actualizada.\n    <br />\n    <br />\n    Su estado actual: <b><%= state.toLowerCase() %></b>.\n    <br />\n    <br />\n    Ultima modificación por: \"<%= updatedBy %>\", el <%= updatedAt %>\n    <br />\n    <br />\n\n    Has click <a class=\"ir\" href=\"<%= url %>\">aquí</a> para acceder a ella.\n\n  </p>\n\n" + template.footer,
    text: "<%= to %> la solicitud \"<%= title %>\" con código de referencia <b><%= code %></b>, a actualizado su estado a <b><%= state.toLowerCase() %></b>.\nlink: <%= url %>"
  };

}).call(this);
