// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var template;

  template = require('./template');

  module.exports = {
    html: "" + template.header + "\n  \n  <p>\n    La solicitud \"<%= title %>\" código: <%= code %> se a actualizado.\n  </p>\n  <a class=\"ir\" href=\"<%= url %>\">Ir a la Solicitud</a>\n\n" + template.footer,
    text: "La solicitud \"<%= title %>\" código: <%= code %> se a actualizado.\nlink: <%= url %>"
  };

}).call(this);
