// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  module.exports = {
    header: "<html>\n  <head>\n    <meta charset=\"UTF-8\">\n    <title></title>\n\n    <style>\n      body {\n        margin: 0;\n        padding: 0;\n        border: none;\n      }\n      table {\n        margin: 0;\n        padding: 0;\n        border: none;\n        width: 100%;\n      }\n      table td.header,\n      table td.content {\n        padding: 20px;\n      }\n      table td.content p {\n        padding: 10px;\n        color: #9da9b9;\n      }\n      table td.content a.ir {\n        background: #00b8cf;\n        margin: 10px;\n        padding: 10px;\n        color: #ffffff;\n        text-decoration: none;\n        text-align: center;\n        font-size: 1em;\n        float: right;\n      }\n      table td.footer p {\n        text-align: center;\n        padding: 5px;\n        color: #ADADAD;\n        border-top: 1px solid #adadad;\n        font-size: 0.9em;\n      }\n    </style>\n\n  </head>\n  <body>\n    <table>\n      <tr bgcolor=\"#2f364a\">\n        <td class=\"header\">\n          <img src=\"http://gestor-movistar.ingeniavps.cl/images/movistar.png\" alt=\"Movistar\">\n        </td>\n      </tr>\n      <tr>\n        <td class=\"content\">",
    footer: "        </td>\n      </tr>\n      <tr>\n        <td class=\"footer\">\n          <p>Gestor de tareas movistar</p>\n        </td>\n      </tr>\n    </table>\n  </body>\n</html>"
  };

}).call(this);
